---
- name: Check remi status
  shell: yum-config-manager remi | grep -q 'enabled = True'
  changed_when: False
  ignore_errors: True
  register: remi_status
  when:
    - ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Check remi status
  shell: yum-config-manager --dump remi | grep -q 'enabled = 1'
  changed_when: False
  ignore_errors: True
  register: remi_status
  when:
    - ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: Install remi
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - remi_status.rc != 0

- name: Install remi
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"
    - remi_status.rc != 0

- name: Enabled remi
  command: yum-config-manager --enable remi
  when:
    - ansible_distribution == "CentOS"
    - remi_status.rc != 0
